site_name: djehuty
site_description: The 4TU.ResearchData and Nikhef repository system
repo_url: https://github.com/4TUResearchData/djehuty
repo_name: 4TUResearchData/djehuty

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy

nav:
  - Home: index.md
  - Configuring & running djehuty: running-djehuty.md
  - Deployment: deployment.md
  - Architecture & design:
      - Knowledge graph: knowledge-graph.md
      - HTTP stack migration: http-migration.md
  - Contributing:
      - Contributing guide: contributing.md
  - API: api.md
  - Contact: contact.md
  - News: news.md

plugins:
  - search
  - include-markdown

markdown_extensions:
  - tables
  - fenced_code
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
