name: "ðŸž Bug report"
description: Use when something is broken or misbehaving (broken functionality).
title: "[BUG]:"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Use when something is broken or misbehaving (broken functionality).
  - type: textarea
    attributes:
      label: Description
      description: A clear and short description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior x Actual behaviour
      description: Tell us what you thought would happen and what actually happens.
  - type: textarea
    attributes:
      label: How to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error -->
  - type: textarea
    attributes:
      label: Your personal set up
      description: Tell us a little about the system you're using or tested this bug in.
      value: |
        - **Operating System**:
        - **Browser**:
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here..
