version: '3'
services:
  djehuty:
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    image: djehuty:latest
    command: '/home/djehuty/start-djehuty.sh'
    volumes:
      - /opt/djehuty/data/:/data/
      - /opt/djehuty/djehuty-config.xml:/djehuty-config.xml
    restart: always
    ports:
      - 9001:8080
    depends_on:
      - sparql
  sparql:
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    image: openlink/virtuoso-opensource-7:7.2.11
    volumes:
      - /container_data/sparql/:/database/
    expose:
      - 8890
      - 1111
    environment:
      DBA_PASSWORD: ""
