version: '3'
services:
  djehuty:
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    image: djehuty:24.6
    command: '/bin/djehuty web -c /djehuty-config.xml'
    read_only: true
    volumes:
      - /opt/djehuty/data/:/data/
      - /opt/djehuty/djehuty-config.xml:/djehuty-config.xml
    restart: always
    ports:
      - 9001:8080
    depends_on:
      - sparql
  sparql:
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    image: openlink/virtuoso-opensource-7:7.2.13
    volumes:
      - /container_data/sparql/:/database/
    expose:
      - 8890
      - 1111
    environment:
      DBA_PASSWORD: ""
