{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?role ?active ?created_date ?email ?first_name ?group_id
                ?uuid ?institution_id ?institution_user_id ?last_name
                ?maximum_file_size ?modified_date ?pending_quota_request ?quota
                ?used_quota ?used_quota_private ?used_quota_public
WHERE {
  GRAPH <{{state_graph}}> {
    ?account             rdf:type                  djht:Account .
    ?account             djht:email                 ?email .
    OPTIONAL { ?account  djht:active                ?active . }
    OPTIONAL { ?account  djht:created_date          ?created_date . }
    OPTIONAL { ?account  djht:first_name            ?first_name . }
    OPTIONAL { ?account  djht:group_id              ?group_id . }
    OPTIONAL { ?account  djht:institution_id        ?institution_id . }
    OPTIONAL { ?account  djht:institution_user_id   ?institution_user_id . }
    OPTIONAL { ?account  djht:last_name             ?last_name . }
    OPTIONAL { ?account  djht:maximum_file_size     ?maximum_file_size . }
    OPTIONAL { ?account  djht:modified_date         ?modified_date . }
    OPTIONAL { ?account  djht:pending_quota_request ?pending_quota_request . }
    OPTIONAL { ?account  djht:quota                 ?quota . }
    OPTIONAL { ?account  djht:used_quota            ?used_quota . }
    OPTIONAL { ?account  djht:used_quota_private    ?used_quota_private . }
    OPTIONAL { ?account  djht:used_quota_public     ?used_quota_public . }
    OPTIONAL { ?account  djht:role                  ?role . }

    ?session             rdf:type                  djht:Session .
    ?session             djht:account               ?account .
    ?session             djht:token                 ?token .

    BIND(STRAFTER(STR(?account), "account:") AS ?uuid)
  }
  FILTER (STR(?token) = "{{token}}")
}
{% endblock %}
