{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?uuid
WHERE {
  GRAPH <{{state_graph}}> {
    ?author     rdf:type             djht:Author ;
                djht:orcid_id        ?orcid_string ;
                djht:account         ?account .
  }
  BIND(STRAFTER(STR(?account), "account:") AS ?uuid)
  ## Wrap in STR for compatibility with Virtuoso.
  FILTER (STR(?orcid_string) = STR({{orcid | safe}}))
}
{% endblock %}
