{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?account_id
WHERE {
  GRAPH <{{state_graph}}> {
    ?row             rdf:type                 djht:AccountOrcid .
    ?row             djht:account_id          ?account_id .
    ?row             djht:orcid_uri           <{{orcid}}> .
  }
}
{% endblock %}
