{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?active ?created_date ?email ?first_name ?group_id ?biography
                ?uuid ?institution_id ?institution_user_id ?last_name
                ?maximum_file_size ?modified_date ?job_title ?location
                ?account_id ?domain ?twitter ?linkedin ?website ?author_uuid
                ?profile_image ?orcid ?full_name
WHERE {
  GRAPH <{{state_graph}}> {
    ?account             rdf:type                   djht:Account .
    OPTIONAL { ?account  djht:id                    ?account_id . }
    OPTIONAL { ?account  djht:active                ?active . }
    OPTIONAL { ?account  djht:job_title             ?job_title . }
    OPTIONAL { ?account  djht:location              ?location . }
    OPTIONAL { ?account  djht:twitter               ?twitter . }
    OPTIONAL { ?account  djht:linkedin              ?linkedin . }
    OPTIONAL { ?account  djht:website               ?website . }
    OPTIONAL { ?account  djht:biography             ?biography . }
    OPTIONAL { ?account  djht:created_date          ?created_date . }
    OPTIONAL { ?account  djht:email                 ?email . }
    OPTIONAL { ?account  djht:first_name            ?first_name . }
    OPTIONAL { ?account  djht:institution_id        ?institution_id . }
    OPTIONAL { ?account  djht:institution_user_id   ?institution_user_id . }
    OPTIONAL { ?account  djht:last_name             ?last_name . }
    OPTIONAL { ?account  djht:profile_image         ?profile_image . }
    OPTIONAL { ?account  djht:maximum_file_size     ?maximum_file_size . }
    OPTIONAL { ?account  djht:modified_date         ?modified_date . }
    OPTIONAL {
      ?group             rdf:type                   djht:InstitutionGroup ;
                         djht:association_criteria  ?domain ;
                         djht:id                    ?group_id .
      ?account           djht:domain                ?domain .
    }
    OPTIONAL {
      ?author            rdf:type                   djht:Author ;
                         djht:account               ?account .
      OPTIONAL { ?author djht:orcid_id              ?orcid . }
      OPTIONAL { ?author djht:full_name             ?full_name . }
    }
  }
  BIND(STRAFTER(STR(?account), "account:") AS ?uuid)
  BIND(COALESCE (STRAFTER(STR(?author), "author:"), "unknown") AS ?author_uuid)

  {%- if account_uuid is not none %}
  FILTER (?account = <account:{{account_uuid}}>)
  {%- endif %}{% if is_active is not none %}
  FILTER (?active = {{is_active}})
  {%- endif %}{% if email is not none %}
  FILTER (LCASE(STR(?email)) = LCASE(STR({{email | safe}})))
  {%- endif %}{% if minimum_account_id is not none %}
  FILTER (?account_id >= {{minimum_account_id}})
  {%- endif %}{% if maximum_account_id is not none %}
  FILTER (?account_id <= {{maximum_account_id}})
  {%- endif %}{% if institution_user_id is not none %}
  FILTER (?institution_user_id <= {{institution_user_id | safe}})
  {%- endif %}
  {% if filters is not none %}{{filters | safe}}{% endif %}

  {%- if search_for is not none %}
  FILTER (CONTAINS (UCASE (STR (?email)),      UCASE ({{search_for | safe}})) ||
          CONTAINS (UCASE (STR (?first_name)), UCASE ({{search_for | safe}})) ||
          CONTAINS (UCASE (STR (?last_name)),  UCASE ({{search_for | safe}})) ||
          CONTAINS (UCASE (STR (?orcid)),      UCASE ({{search_for | safe}})))
  {%- endif %}
}
{% endblock %}
