{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?role ?active ?created_date ?email ?first_name ?group_id
                ?uuid ?institution_id ?institution_user_id ?last_name
                ?maximum_file_size ?modified_date ?domain ?profile_image
                ?quota
WHERE {
  GRAPH <{{state_graph}}> {
    ?account             rdf:type                  djht:Account .
    ?account             djht:email                 ?email .
    OPTIONAL { ?account  djht:active                ?active . }
    OPTIONAL { ?account  djht:created_date          ?created_date . }
    OPTIONAL { ?account  djht:first_name            ?first_name . }
    OPTIONAL { ?account  djht:institution_id        ?institution_id . }
    OPTIONAL { ?account  djht:institution_user_id   ?institution_user_id . }
    OPTIONAL { ?account  djht:last_name             ?last_name . }
    OPTIONAL { ?account  djht:maximum_file_size     ?maximum_file_size . }
    OPTIONAL { ?account  djht:profile_image         ?profile_image . }
    OPTIONAL { ?account  djht:modified_date         ?modified_date . }
    OPTIONAL { ?account  djht:role                  ?role . }
    OPTIONAL { ?account  djht:quota                 ?quota . }

    ?session             rdf:type                  djht:Session .
    ?session             djht:account               ?account .
    ?session             djht:token                 ?token .
    {%- if mfa_token is none %}
    ?session             djht:active                "true"^^xsd:boolean .
    {%- else %}
    ?session             djht:active                "false"^^xsd:boolean .
    ?session             djht:mfa_token             {{mfa_token}} .
    {%- endif %}

    OPTIONAL {
      ?group             rdf:type                   djht:InstitutionGroup ;
                         djht:association_criteria  ?domain ;
                         djht:id                    ?group_id .
      ?account           djht:domain                ?domain .
    }

    BIND(STRAFTER(STR(?account), "account:") AS ?uuid)
  }
  ## Wrap in STR for compatibility with Virtuoso.
  FILTER (STR(?token) = STR({{token | safe}}))
}
{% endblock %}
