{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?uuid
WHERE {
  GRAPH <{{state_graph}}> {
    ?row             rdf:type                 djht:AccountOrcid .
    ?row             djht:account             ?account .
    ?row             djht:orcid_uri           <{{orcid}}> .
  }
  BIND(STRAFTER(STR(?account), "account:") AS ?uuid)
}
{% endblock %}
