{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?file ?bytes
WHERE {
  GRAPH <{{state_graph}}> {

    ?container      rdf:type                      djht:ArticleContainer .
    ?container      djht:account_id               ?account_id .

    {
      ?container    djht:draft                    ?article .
    } UNION {
      ?container    djht:published_versions/rdf:rest*/rdf:first ?article .
    }

    ?article        rdf:type                      djht:Article .
    ?article        djht:files/rdf:rest*/rdf:first ?file .

    ?file           rdf:type                      djht:File .
    ?file           djht:size                     ?bytes .
  }
  FILTER (?account_id = {{account_id}})
}
{% endblock %}
