{% extends "prefixes.sparql" %}
{% block query %}
SELECT ?account_id ?uuid ?token ?name ?created_date ?editable
WHERE {
  GRAPH <{{state_graph}}> {
    ?session             rdf:type                  sg:Session .
    ?session             col:account_id            ?account_id .
    ?session             col:token                 ?token .
    OPTIONAL { ?session  col:name                  ?name . }
    OPTIONAL { ?session  col:created_date          ?created_date . }
    OPTIONAL { ?session  col:editable              ?editable . }
  }
  FILTER (?account_id = {{account_id}})
  {%- if session_uuid is not none: %}
  FILTER (?session = <session:{{session_uuid}}>)
  {%- endif %}

  BIND (STRAFTER(STR(?session), "session:") AS ?uuid)
}
ORDER BY DESC(?created_date)
{% endblock %}
