{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?file ?bytes
WHERE {
  GRAPH <{{state_graph}}> {
    ?article        rdf:type                      sg:Article .
    ?article        col:account_id                ?account_id .
    ?article        col:files/rdf:rest*/rdf:first ?file .

    ?file           rdf:type                      sg:File .
    ?file           col:size                      ?bytes .
  }
  FILTER (?account_id = {{account_id}})
}
{% endblock %}
