{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?uuid
WHERE {
  GRAPH <{{state_graph}}> {
    ?account    rdf:type             djht:Account .
    ?account    djht:orcid_uri       <{{orcid}}> .
  }
  BIND(STRAFTER(STR(?account), "account:") AS ?uuid)
}
{% endblock %}
