{% extends "prefixes.sparql" %}
{% block query %}
SELECT (SUM(?bytes) AS ?bytes)
WHERE {
  GRAPH <{{state_graph}}> {
    ?file           rdf:type            sg:File .
    ?file           col:id              ?file_id .
    ?file           col:size            ?bytes .

    ?link           rdf:type            sg:ArticleFile .
    ?link           col:article_id      ?article_id .
    ?link           col:file_id         ?file_id .
  }
  FILTER (?article_id = {{article_id}})
}
{% endblock %}
