{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?article_id ?article_version_id ?type ?ip_name
WHERE {
  GRAPH <{{state_graph}}> {
    ?field             rdf:type                 sg:ArticleEmbargoOption .
    ?field             col:article_id           ?article_id .
    ?field             col:article_version_id   ?article_version_id .
    OPTIONAL { ?field  col:type                 ?type . }
    OPTIONAL { ?field  col:ip_name              ?ip_name . }
  }
{%- if filters is not none %}{{ filters }}{% endif %}
}
{% endblock %}
