{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?article_id (SUM(?{{item_type}}) / COUNT(?version)) AS ?{{item_type}} ?title ?figshare_url
WHERE {
  GRAPH <{{state_graph}}> {
    ?container      rdf:type                     djht:ArticleContainer .
    ?container      col:article_id               ?article_id .
    ?container      col:total_{{item_type}}      ?{{item_type}} .
    ?container      col:latest_published_version ?article .

    ?article        col:title                    ?title .
    ?article        col:version                  ?version .
    ?article        col:figshare_url             ?figshare_url .
    ?article        col:published_date           ?published_date .
    OPTIONAL { ?article      col:group_id        ?group_id . }
  }
{% if filters is not none %}{{ filters }}{% endif %}
}
{% endblock %}
