{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?article_id (SUM(?{{item_type}}) / COUNT(?version)) AS ?{{item_type}} ?title ?figshare_url
WHERE {
  GRAPH <{{state_graph}}> {
    ?container      rdf:type                      djht:ArticleContainer .
    ?container      djht:article_id               ?article_id .
    ?container      djht:total_{{item_type}}      ?{{item_type}} .
    ?container      djht:latest_published_version ?article .

    ?article        djht:title                    ?title .
    ?article        djht:version                  ?version .
    ?article        djht:figshare_url             ?figshare_url .
    ?article        djht:published_date           ?published_date .
    OPTIONAL { ?article      djht:group_id        ?group_id . }
  }
{% if filters is not none %}{{ filters }}{% endif %}
}
{% endblock %}
