{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?name          ?size          ?is_link_only
                ?id            ?download_url  ?supplied_md5
                ?computed_md5  ?viewer_type   ?preview_state
                ?status        ?upload_url    ?upload_token
                ?order_index   ?uuid          ?filesystem_location
WHERE {
  GRAPH <{{state_graph}}> {
    ?file              rdf:type                djht:File .
    {% if article_uri is not none %}
    ?article_uri       rdf:type                djht:Article ;
                       col:files               ?files .
    ?files             rdf:rest*               ?rest .
    ?rest              rdf:first               ?file ;
                       col:index               ?order_index .
    {% endif %}{% if account_id is not none %}
    ?article_uri       col:container            ?container .
    ?container         rdf:type/rdfs:subClassOf djht:Container ;
                       col:account_id           {{account_id}} .
    {% endif %}
    OPTIONAL { ?file  col:id                   ?id . }
    OPTIONAL { ?file  col:name                 ?name . }
    OPTIONAL { ?file  col:filesystem_location  ?filesystem_location . }
    OPTIONAL { ?file  col:size                 ?size . }
    OPTIONAL { ?file  col:is_link_only         ?is_link_only . }
    OPTIONAL { ?file  col:download_url         ?download_url . }
    OPTIONAL { ?file  col:supplied_md5         ?supplied_md5 . }
    OPTIONAL { ?file  col:computed_md5         ?computed_md5 . }
    OPTIONAL { ?file  col:viewer_type          ?viewer_type . }
    OPTIONAL { ?file  col:preview_state        ?preview_state . }
    OPTIONAL { ?file  col:status               ?status . }
    OPTIONAL { ?file  col:upload_url           ?upload_url . }
    OPTIONAL { ?file  col:upload_token         ?upload_token . }

    BIND(STRAFTER(STR(?file), "file:") AS ?uuid)
  }
{%- if article_uri is not none %}
  FILTER (?article_uri = <{{article_uri}}>)
{%- endif %}
{%- if file_uuid is not none %}
  FILTER (?file = <file:{{file_uuid}}>)
{%- endif %}
{%- if filters is not none %}{{ filters }}{% endif %}
}
{% endblock %}
