{% extends "prefixes.sparql" %}
{% block query %}
{%- if return_count %}
SELECT COUNT(DISTINCT ?article) AS ?articles
{%- else %}
SELECT DISTINCT ?account_id ?citation ?confidential_reason
                ?created_date ?custom_fields_id ?defined_type ?defined_type_name
                ?description ?doi ?embargo_date ?embargo_options_id 
                ?embargo_reason ?embargo_title ?embargo_type ?figshare_url
                ?funding ?funding_id ?group_id ?has_linked_file ?article_id
                ?institution_id ?is_active ?is_confidential ?is_embargoed
                ?is_metadata_record ?is_public ?license_id ?license_name
                ?license_url ?metadata_reason ?modified_date ?published_date
                ?resource_doi ?resource_title ?size ?status ?tags_id ?thumb
                ?timeline_posted ?timeline_publisher_acceptance
                ?timeline_publisher_publication ?timeline_first_online
                ?timeline_revision ?timeline_submission ?title ?url
                ?url_private_api ?url_private_html ?url_public_api
                ?url_public_html ?version ?publisher ?language ?time_coverage
                ?geolocation ?longitude ?latitude ?format ?organizations
                ?data_link ?derived_from ?same_as ?contributors
                ?license_remarks ?article_version_id
{%endif%}
WHERE {
  GRAPH <{{state_graph}}> {
    ?article            rdf:type                 sg:Article .
    ?article            col:article_id           ?article_id .
    ?article            col:article_version_id   ?article_version_id .
    ?article            col:timeline_id          ?timeline_id .
    ?article            col:title                ?title .

    ?article            col:account_id           ?account_id .
    ?account            rdf:type                 sg:Account .
    ?account            col:id                   ?account_id .

    {%- if collection_version_id is not none %}
    ?link               rdf:type                 sg:CollectionArticle .
    ?link               col:article_version_id   ?article_version_id .
    ?link               col:collection_version_id {{collection_version_id}} .
    {%- endif %}
    {%- if category_ids is not none: %}
    ?category_link      rdf:type                 sg:ArticleCategory .
    ?category_link      col:category_id          ?category_id .
    ?category_link      col:article_version_id   ?article_version_id .

    ?category           rdf:type                 sg:Category .
    ?category           col:id                   ?category_id .
    ?category           col:parent_id            ?parent_category_id .
    {%- endif %}
    OPTIONAL {
        ?timeline           rdf:type                 sg:Timeline .
        ?timeline           col:id                   ?timeline_id .

        OPTIONAL { ?timeline col:firstonline          ?timeline_first_online . }
        OPTIONAL { ?timeline col:publisheracceptance  ?timeline_publisher_acceptance . }
        OPTIONAL { ?timeline col:publisherpublication ?timeline_publisher_publication . }
        OPTIONAL { ?timeline col:submission           ?timeline_submission . }
        OPTIONAL { ?timeline col:posted               ?timeline_posted . }
        OPTIONAL { ?timeline col:revision             ?timeline_revision . }
    }

    OPTIONAL {
        ?license            rdf:type                  sg:License .
        ?license            col:id                    ?license_id .
        ?license            col:name                  ?license_name .
        ?license            col:url                   ?license_url .
        ?article            col:license_id            ?license_id .
    }

    OPTIONAL { ?article col:citation              ?citation . }
    OPTIONAL { ?article col:confidential_reason   ?confidential_reason . }
    OPTIONAL { ?article col:created_date          ?created_date . }
    OPTIONAL { ?article col:custom_fields_id      ?custom_fields_id . }
    OPTIONAL { ?article col:defined_type          ?defined_type . }
    OPTIONAL { ?article col:defined_type_name     ?defined_type_name . }
    OPTIONAL { ?article col:description           ?description . }
    OPTIONAL { ?article col:doi                   ?doi . }
    OPTIONAL { ?article col:embargo_date          ?embargo_date . }
    OPTIONAL { ?article col:embargo_options_id    ?embargo_options_id . }
    OPTIONAL { ?article col:embargo_reason        ?embargo_reason . }
    OPTIONAL { ?article col:embargo_title         ?embargo_title . }
    OPTIONAL { ?article col:embargo_type          ?embargo_type . }
    OPTIONAL { ?article col:figshare_url          ?figshare_url . }
    OPTIONAL { ?article col:funding               ?funding . }
    OPTIONAL { ?article col:funding_id            ?funding_id . }
    OPTIONAL { ?article col:group_id              ?group_id . }
    OPTIONAL { ?article col:handle                ?handle . }
    OPTIONAL { ?article col:has_linked_file       ?has_linked_file . }
    OPTIONAL { ?account col:institution_id        ?institution_id . }
    OPTIONAL { ?article col:is_active             ?is_active . }
    OPTIONAL { ?article col:is_confidential       ?is_confidential . }
    OPTIONAL { ?article col:is_embargoed          ?is_embargoed . }
    OPTIONAL { ?article col:is_metadata_record    ?is_metadata_record . }
    OPTIONAL { ?article col:is_public             ?is_public . }
    OPTIONAL { ?article col:metadata_reason       ?metadata_reason . }
    OPTIONAL { ?article col:modified_date         ?modified_date . }
    OPTIONAL { ?article col:published_date        ?published_date . }
    OPTIONAL { ?article col:resource_doi          ?resource_doi . }
    OPTIONAL { ?article col:resource_title        ?resource_title . }
    OPTIONAL { ?article col:size                  ?size . }
    OPTIONAL { ?article col:status                ?status . }
    OPTIONAL { ?article col:tags_id               ?tags_id . }
    OPTIONAL { ?article col:thumb                 ?thumb . }
    OPTIONAL { ?article col:url                   ?url . }
    OPTIONAL { ?article col:url_private_api       ?url_private_api . }
    OPTIONAL { ?article col:url_private_html      ?url_private_html . }
    OPTIONAL { ?article col:url_public_api        ?url_public_api . }
    OPTIONAL { ?article col:url_public_html       ?url_public_html . }
    OPTIONAL { ?article col:version               ?version . }
    {#- Custom fields. #}
    OPTIONAL { ?article col:publisher             ?publisher . }
    OPTIONAL { ?article col:language              ?language . }
    OPTIONAL { ?article col:time_coverage         ?time_coverage . }
    OPTIONAL { ?article col:geolocation           ?geolocation . }
    OPTIONAL { ?article col:longitude             ?longitude . }
    OPTIONAL { ?article col:latitude              ?latitude . }
    OPTIONAL { ?article col:format                ?format . }
    OPTIONAL { ?article col:organizations         ?organizations . }
    OPTIONAL { ?article col:data_link             ?data_link . }
    OPTIONAL { ?article col:same_as               ?same_as . }
    OPTIONAL { ?article col:derived_from          ?derived_from . }
    OPTIONAL { ?article col:contributors          ?contributors . }
    OPTIONAL { ?article col:license_remarks       ?license_remarks . }
  }
{%- if account_id is not none: %}
FILTER (?account_id = {{account_id}})
{%- else: %}
FILTER (STR(?published_date) != "NULL")
{%- endif %}
{% if filters is not none %}{{ filters }}{% endif %}
}
{% endblock %}
