{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT (STRAFTER(STR(?associated_author), ":") AS ?associated_author_uuid)
                ?full_name ?is_active
WHERE {
  GRAPH <{{state_graph}}> {
    ?item          djht:is_public                    true ;
                   djht:authors/rdf:rest*/rdf:first  <{{author_uri}}> ,
                                                     ?associated_author .
    ?associated_author djht:full_name                ?full_name ;
                   djht:is_active                    ?is_active .
    FILTER (?associated_author != <{{author_uri}}>)
  }
}
ORDER BY (?full_name)
{% endblock %}
