{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?first_name      ?full_name       ?group_id
                ?id              ?institution_id  ?is_active
                ?is_public       ?job_title       ?last_name
                ?orcid_id        ?url_name        ?order_index
WHERE {
  GRAPH <{{state_graph}}> {
    ?author            rdf:type                 sg:Author ;
                       col:id                   ?id .
    {%- if item_uri is not none %}
    ?item_uri          rdf:type                 sg:{{prefix}} ;
                       col:authors              ?authors .
    ?authors           rdf:rest*                ?rest .
    ?rest              rdf:first                ?author ;
                       col:index                ?order_index .
    {%- endif %}
    {%- if account_id is not none %}
    ?container         rdf:type                 sg:{{prefix}}Container .
    {%- if is_published %}
    ?container         col:published_versions/rdf:rest*/rdf:first ?item_uri .
    {%- else %}
    ?container         col:draft                ?item_uri .
    {%- endif %}
    ?container         col:account_id           {{account_id}} .
    {%- endif %}
    OPTIONAL { ?author col:first_name           ?first_name . }
    OPTIONAL { ?author col:full_name            ?full_name . }
    OPTIONAL { ?author col:group_id             ?group_id . }
    OPTIONAL { ?author col:institution_id       ?institution_id . }
    OPTIONAL { ?author col:is_active            ?is_active . }
    OPTIONAL { ?author col:is_public            ?is_public . }
    OPTIONAL { ?author col:job_title            ?job_title . }
    OPTIONAL { ?author col:last_name            ?last_name . }
    OPTIONAL { ?author col:orcid_id             ?orcid_id . }
    OPTIONAL { ?author col:url_name             ?url_name . }
  }
{%- if item_uri is not none %}
  FILTER (?item_uri = <{{item_uri}}>)
{% endif %}
{% if filters is not none %}{{ filters }}{% endif %}
}
{% endblock %}
