{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?id ?uuid ?title ?parent_id ?source_id ?taxonomy_id
WHERE {
  GRAPH <{{state_graph}}> {
    ?category            rdf:type          djht:Category .
    ?category            djht:id           ?id .
    ?category            djht:title        ?title .
    OPTIONAL { ?category djht:parent_id    ?parent_id . }
    OPTIONAL { ?category djht:source_id    ?source_id . }
    OPTIONAL { ?category djht:taxonomy_id  ?taxonomy_id . }
  }
  BIND(STRAFTER(STR(?category), "category:") AS ?uuid)
  FILTER (?id = {{category_id}})
{%- if filters is not none %}{{ filters | safe }}{% endif %}
}
{% endblock %}
