{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?id ?uuid ?parent_id ?parent_uuid ?title ?source_id ?taxonomy_id ?classification_code
WHERE {
  GRAPH <{{state_graph}}> {
    ?category         rdf:type                           djht:Category ;
                      djht:id                            ?id ;
                      djht:title                         ?title .
    OPTIONAL {
      ?category        djht:parent_id                    ?parent_id .
      ?parent_category djht:id                           ?parent_id .

      BIND(STRAFTER(STR(?parent_category), "category:") AS ?parent_uuid)
    }
    OPTIONAL { ?category  djht:classification_code       ?classification_code . }
    OPTIONAL { ?category  djht:source_id                 ?source_id . }
    OPTIONAL { ?category  djht:taxonomy_id               ?taxonomy_id . }
    {%- if item_uri is not none %}
    ?item_uri        djht:categories/rdf:rest*/rdf:first ?category .
    {%- if account_uuid is not none %}
    ?container         rdf:type/rdfs:subClassOf         djht:Container .
    {
      ?container         djht:account             <account:{{account_uuid}}> .
    } UNION {
      ?dataset           djht:container ?container .
      ?dataset           djht:collaborators/rdf:rest*/rdf:first ?collaborator .
      ?collaborator      djht:account ?account .
      ?collaborator      djht:metadata_read  "true"^^xsd:boolean .
    }
    {%- if is_published %}
    ?container         djht:published_versions/rdf:rest*/rdf:first ?item_uri .
    {%- else %}
    ?container         djht:draft                        ?item_uri .
    {%- endif %}
    {%- endif %}
    {%- endif %}

    BIND(STRAFTER(STR(?category), "category:") AS ?uuid)
  }
{%- if item_uri is not none %}
  FILTER (?item_uri = <{{item_uri}}>)
{%- endif %}
{%- if filters is not none %}{{ filters | safe }}{% endif %}
}
{% endblock %}
