{% extends "prefixes.sparql" %}
{% block query %}
SELECT COUNT(DISTINCT ?datasets) AS ?datasets

WHERE {
  GRAPH <{{state_graph}}> {
    <{{collection_uri}}> rdf:type                         djht:Collection ;
                         djht:datasets/rdf:rest*/rdf:first ?datasets .
  }
}
{% endblock %}
