{% extends "prefixes.sparql" %}
{% block query %}
SELECT COUNT(DISTINCT ?articles) AS ?articles

WHERE {
  GRAPH <{{state_graph}}> {
    <{{collection_uri}}> rdf:type                         djht:Collection ;
                         col:articles/rdf:rest*/rdf:first ?articles .
  }
}
{% endblock %}
