{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?collection_id ?title
WHERE {
  GRAPH <{{state_graph}}> {
    ?collection_container rdf:type                                         djht:CollectionContainer ;
                          col:collection_id                                ?collection_id ;
                          col:latest_published_version                     ?collection .
    ?collection           rdf:type                                         djht:Collection ;
                          col:title                                        ?title ;
                          col:articles/rdf:rest*/rdf:first/col:article_id  {{article_id}} .
  }   
}
{% endblock %}