{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?account_id ?resource_id ?resource_doi ?resource_title
                ?resource_link ?resource_version ?version ?description
                ?institution_id ?group_id ?is_public
                ?citation ?group_resource_id ?custom_fields_id ?modified_date
                ?created_date ?timeline_posted ?timeline_publisher_acceptance
                ?timeline_publisher_publication ?timeline_first_online
                ?timeline_revision ?timeline_submission ?id ?title ?doi ?handle
                ?url ?published_date
WHERE {
  GRAPH <{{state_graph}}> {
    ?collection            rdf:type                   sg:Collection .
    ?collection            col:collection_id          ?id .
    ?collection            col:timeline_id            ?timeline_id .

    OPTIONAL {
        ?timeline           rdf:type                  sg:Timeline .
        ?timeline           col:id                    ?timeline_id .

        OPTIONAL { ?timeline col:firstonline          ?timeline_first_online . }
        OPTIONAL { ?timeline col:publisheracceptance  ?timeline_publisher_acceptance . }
        OPTIONAL { ?timeline col:publisherpublication ?timeline_publisher_publication . }
        OPTIONAL { ?timeline col:submission           ?timeline_submission . }
        OPTIONAL { ?timeline col:posted               ?timeline_posted . }
        OPTIONAL { ?timeline col:revision             ?timeline_revision . }
    }

    OPTIONAL { ?collection   col:account_id           ?account_id . }
    OPTIONAL { ?collection   col:resource_id          ?resource_id . }
    OPTIONAL { ?collection   col:resource_doi         ?resource_doi . }
    OPTIONAL { ?collection   col:resource_title       ?resource_title . }
    OPTIONAL { ?collection   col:resource_link        ?resource_link . }
    OPTIONAL { ?collection   col:resource_version     ?resource_version . }
    OPTIONAL { ?collection   col:version              ?version . }
    OPTIONAL { ?collection   col:description          ?description . }
    OPTIONAL { ?collection   col:institution_id       ?institution_id . }
    OPTIONAL { ?collection   col:group_id             ?group_id . }
    OPTIONAL { ?collection   col:is_public            ?is_public . }
    OPTIONAL { ?collection   col:citation             ?citation . }
    OPTIONAL { ?collection   col:group_resource_id    ?group_resource_id . }
    OPTIONAL { ?collection   col:custom_fields_id     ?custom_fields_id . }
    OPTIONAL { ?collection   col:modified_date        ?modified_date . }
    OPTIONAL { ?collection   col:created_date         ?created_date . }
    OPTIONAL { ?collection   col:title                ?title . }
    OPTIONAL { ?collection   col:doi                  ?doi . }
    OPTIONAL { ?collection   col:handle               ?handle . }
    OPTIONAL { ?collection   col:url                  ?url . }
    OPTIONAL { ?collection   col:published_date       ?published_date . }
  }
{%- if filters is not none %}{{ filters }}{% endif %}
}
{% endblock %}
