{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?account_uuid ?container_uuid ?version ?container_uri
                (?item_uri AS ?uri) ?uuid
WHERE {
  GRAPH <{{state_graph}}> {
    ?container_uri       rdf:type/rdfs:subClassOf djht:Container .
    ?container_uri       djht:account             ?account .
    {%- if is_published is none and is_latest is none %}
    ?item_uri            djht:container           ?container_uri .
    {%- elif is_published %}
    {%- if is_latest %}
    ?container_uri       djht:latest_published_version ?item_uri .
    {%- else %}
    ?container_uri       djht:published_versions/rdf:rest*/rdf:first ?item_uri .
    {%- endif %}
    {%- else %}
    ?container_uri       djht:draft                ?item_uri .
    {%- endif %}

{%- if account_uuid is not none and not disable_collaboration: %}
    OPTIONAL {
      ?collaborator       rdf:type            djht:Collaborator .
      ?collaborator       djht:item           ?item_uri .
      ?collaborator       djht:account        ?collaborator_account .
      ?collaborator       djht:metadata_read  "true"^^xsd:boolean .
    }
{%- endif %}
    OPTIONAL { ?item_uri djht:version              ?version . }
    BIND(STRAFTER(STR(?container_uri), "container:") AS ?container_uuid)
    BIND(STRAFTER(STR(?account), "account:")         AS ?account_uuid)
    BIND(STRAFTER(STR(?item_uri), ":")               AS ?uuid)
  }
{%- if account_uuid is not none: %}
  {%- if disable_collaboration %}
FILTER (?account = <account:{{account_uuid}}>)
  {%- else %}
FILTER (?account = <account:{{account_uuid}}> ||
        ?collaborator_account = <account:{{account_uuid}}>)
  {%- endif %}
{%- endif %}
{%- if container_uri is not none: %}
FILTER (?container_uri = <{{container_uri}}>)
{%- endif %}
{%- if item_uuid is not none %}
FILTER (STRAFTER(STR(?item_uri), ":") = STR("{{item_uuid}}"))
{%- endif %}
}
{% endblock %}
