{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?account_uuid ?draft ?doi ?latest_published_version ?first_online_date
       ?totals_created_at ?total_downloads ?total_views ?total_shares ?total_cites
       ?latest_published_version_number ?container_uuid

WHERE {
  GRAPH <{{state_graph}}> {
    ?container            rdf:type                      djht:{{item_type.capitalize()}}Container .
    OPTIONAL { ?container djht:account                  ?account .           }
    OPTIONAL { ?container djht:draft                    ?draft .             }
    OPTIONAL { ?container djht:doi                      ?doi .               }
    OPTIONAL { ?container djht:first_online_date        ?first_online_date . }
    OPTIONAL { ?container djht:totals_created_at        ?totals_created_at . }
    OPTIONAL { ?container djht:total_downloads          ?total_downloads .   }
    OPTIONAL { ?container djht:total_views              ?total_views .       }
    OPTIONAL { ?container djht:total_shares             ?total_shares .      }
    OPTIONAL { ?container djht:total_cites              ?total_cites .       }
    OPTIONAL { ?container djht:latest_published_version ?latest_published_version .
               OPTIONAL { ?latest_published_version djht:version   ?latest_published_version_number . }
             }

    BIND(STRAFTER(STR(?account), "account:") AS ?account_uuid)
    BIND(STRAFTER(STR(?container), "container:") AS ?container_uuid)
  }
  FILTER(?container = <container:{{container_uuid}}>)
}
{% endblock %}
