{% extends "prefixes.sparql" %}
{% block query %}
SELECT ?container_uuid

WHERE {
  GRAPH <{{state_graph}}> {
    ?container  a                      djht:{{item_type.capitalize()}}Container ;
                djht:{{item_type}}_id  {{container_id}} .
    BIND(STRAFTER(STR(?container), "container:") AS ?container_uuid)
  }
}
LIMIT 1
{% endblock %}
