{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?name          ?value         ?default_value
                ?id            ?placeholder   ?max_length
                ?min_length    ?field_type    ?is_multiple
                ?is_mandatory
WHERE {
  GRAPH <{{state_graph}}> {
    ?field             rdf:type                 sg:CustomField .
    ?field             col:original_name        ?name .
    ?field             col:predicate            ?predicate .

    {%- if item_uri is not none %}
    ?item_uri          rdf:type                 sg:{{prefix}} ;
                       ?predicate               ?value .
    {%- endif %}
    OPTIONAL { ?field  col:default_value        ?default_value . }
    OPTIONAL { ?field  col:placeholder          ?placeholder . }
    OPTIONAL { ?field  col:max_length           ?max_length . }
    OPTIONAL { ?field  col:min_length           ?min_length . }
    OPTIONAL { ?field  col:field_type           ?field_type . }
    OPTIONAL { ?field  col:is_multiple          ?is_multiple . }
    OPTIONAL { ?field  col:is_mandatory         ?is_mandatory . }
  }
{%- if item_uri is not none %}
  FILTER (?item_uri = <{{item_uri}}>)
{%- endif %}
{%- if filters is not none %}{{ filters }}{% endif %}
}
{% endblock %}
