{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?name          ?value         ?default_value
                ?id            ?placeholder   ?max_length
                ?min_length    ?field_type    ?is_multiple
                ?is_mandatory
WHERE {
  GRAPH <{{state_graph}}> {
    ?field             rdf:type                 djht:CustomField .
    ?field             djht:original_name        ?name .
    ?field             djht:predicate            ?predicate .

    {%- if item_uri is not none %}
    ?item_uri          rdf:type                 djht:{{prefix}} ;
                       ?predicate               ?value .
    {%- endif %}
    OPTIONAL { ?field  djht:default_value        ?default_value . }
    OPTIONAL { ?field  djht:placeholder          ?placeholder . }
    OPTIONAL { ?field  djht:max_length           ?max_length . }
    OPTIONAL { ?field  djht:min_length           ?min_length . }
    OPTIONAL { ?field  djht:field_type           ?field_type . }
    OPTIONAL { ?field  djht:is_multiple          ?is_multiple . }
    OPTIONAL { ?field  djht:is_mandatory         ?is_mandatory . }
  }
{%- if item_uri is not none %}
  FILTER (?item_uri = <{{item_uri}}>)
{%- endif %}
{%- if filters is not none %}{{ filters | safe }}{% endif %}
}
{% endblock %}
