{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?blank_before rdf:rest ?blank_node .
    ?blank_node   djht:index ?blank_index .
    ?blank_node   rdf:first ?blank_first .
    ?blank_node   rdf:type  rdf:List .
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    ?blank_before rdf:rest ?blank_after .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    <{{subject}}> {{predicate | safe}}/rdf:rest* ?blank_node .
    ?blank_node rdf:first {{first | safe}} .
    {
      ?blank_before rdf:rest ?blank_node .
    } UNION { 
      <{{subject}}> {{predicate | safe}} ?blank_node .
    }
    ?blank_node rdf:rest   ?blank_after .
    ?blank_node djht:index ?blank_index .
    ?blank_node rdf:first  ?blank_first .
  }
}
{% endblock %}
