{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?collection   ?predicate           ?object .
    ?list         djht:index            ?list_index .
    ?list         ?any                 ?list_item .

    ?container    djht:draft           ?collection .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?container    rdf:type             djht:CollectionContainer ;
                  djht:account          <account:{{account_uuid}}> ;
                  djht:draft            ?collection .

    ?collection   ?predicate           ?object .
    OPTIONAL {
      ?collection ?list_predicate      ?list .
      ?list        rdf:type             rdf:List ;
                   djht:index            ?list_index ;
                   rdf:rest*/rdf:first  ?list_item .
    }
  }

  FILTER (?container = <{{container_uri}}>)
}
{% endblock %}
