{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?session  ?predicate     ?object .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?session    rdf:type       djht:Session .
    ?session    ?predicate     ?object .
  }
}
{% endblock %}
