{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
    GRAPH <{{state_graph}}> {
    ?group      ?predicate          ?object .
    ?account    ?account_predicate  ?account_object .
    }
}
WHERE {
    GRAPH <{{state_graph}}> {
        ?group      rdf:type            djht:Group .
        ?group      djht:is_inferred    "true"^^xsd:boolean .
        ?group      ?predicate          ?object .
        ?account    rdf:type            djht:Account .
        ?account    djht:is_inferred    "true"^^xsd:boolean .
        ?account    ?account_predicate  ?account_object .
        {?account    djht:is_member_of   ?group .} UNION {?account    djht:is_supervisor_of   ?group .}
    }
}
{% endblock %}
