{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?row     rdf:type       sg:ArticleFile .
    ?row     col:id         ?row_id .
    ?row     col:article_id ?article_id .
    ?row     col:file_id    ?file_id .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?row     rdf:type       sg:ArticleFile .
    ?row     col:id         ?row_id .
    ?row     col:article_id ?article_id .
    ?row     col:file_id    ?file_id .

    ?article rdf:type       sg:Article .
    ?article col:article_id ?article_id .
    ?article col:account_id ?account_id .
  }
  FILTER (?article_id = {{article_id}})
  FILTER (?account_id = {{account_id}})
  {% if file_id is not none %}
  FILTER (?file_id = {{file_id}})
  {% endif %}
}
{% endblock %}
