{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?row     rdf:type          sg:CollectionArticle .
    ?row     col:id            ?row_id .
    ?row     col:collection_version_id ?collection_version_id .
    ?row     col:article_version_id ?article_version_id .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?row     rdf:type          sg:CollectionArticle .
    ?row     col:id            ?row_id .
    ?row     col:collection_version_id ?collection_version_id .
    ?row     col:article_version_id ?article_version_id .

    ?item    rdf:type          sg:Collection .
    ?item    col:collection_version_id ?collection_version_id .
    ?item    col:account_id    ?account_id .
  }
  FILTER (?collection_version_id = {{collection_version_id}})
  FILTER (?account_id = {{account_id}})
  {%- if article_version_id is not none %}
  FILTER (?article_version_id = {{article_version_id}})
  {%- endif %}
}
{% endblock %}
