{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?collection  ?predicate     ?object .
    ?link        ?p             ?o .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?collection  rdf:type          sg:Collection .
    ?collection  col:collection_version_id ?collection_version_id .
    ?collection  col:account_id    {{account_id}} .
    ?collection  ?predicate        ?object .

    OPTIONAL {
      ?link      rdf:type          sg:CollectionArticle .
      ?link      col:collection_version_id ?collection_version_id .
      ?link      ?p                ?o .
    }

    FILTER (?collection_version_id = {{collection_version_id}})
  }
}
{% endblock %}
