{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?reference  ?predicate     ?object .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?article    rdf:type       sg:Article .
    ?article    col:article_version_id {{article_version_id}} .
    ?article    col:account_id {{account_id}} .

    ?reference  rdf:type       sg:ArticleReference .
    ?reference  col:article_version_id {{article_version_id}} .
    ?reference  col:url        "{{url}}"^^xsd:string .
    ?reference  ?predicate     ?object .
  }
}
{% endblock %}
