{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?account     djht:{{predicate}}   ?object .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?account    rdf:type             djht:Account ;
                djht:{{predicate}}    ?object .
  }
  FILTER (?account = <account:{{account_uuid}}>)
}
{% endblock %}
