{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?session  ?predicate     ?object .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?session    rdf:type       sg:Session .
    ?session    col:account_id ?account_id .
    ?session    ?predicate     ?object .

    FILTER (?session = <session:{{session_uuid}}>)
    FILTER (?account_id = {{account_id}})
  }
}
{% endblock %}
