{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?row     rdf:type             sg:AccountCategory .
    ?row     col:account_id       ?account_id .
    ?row     col:category_id      ?category_id .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?row     rdf:type             sg:AccountCategory .
    ?row     col:account_id       ?account_id .
    ?row     col:category_id      ?category_id .
  }
  FILTER (?account_id = {{account_id}})
  {%- if category_id is not none %}
  FILTER (?category_id = {{category_id}})
  {%- endif %}
}
{% endblock %}
