{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?account    djht:group          ?group .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    VALUES ?id { {{ group_ids | safe }} }
    ?group      rdf:type            djht:InstitutionGroup .
    ?group      djht:id             ?id .
    ?account    djht:group          ?group .
  }
}
{% endblock %}
