{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?item         djht:{{predicate}}    ?item_list .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?container    rdf:type/rdfs:subClassOf djht:Container ;
                  djht:account_id           ?account_id ;
                  djht:draft                ?item .
    ?item         djht:{{predicate}}        ?item_list .
  }
  FILTER (?account_id = {{account_id}})
  FILTER (?container  = <{{container_uri}}>)
}
{% endblock %}
