{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?row     rdf:type             djht:{{prefix}}Category .
    ?row     djht:{{item_type}}_version_id ?item_id .
    ?row     djht:category_id      ?category_id .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?row     rdf:type             djht:{{prefix}}Category .
    ?row     djht:{{item_type}}_version_id ?item_id .
    ?row     djht:category_id      ?category_id .

    ?item    rdf:type             djht:{{prefix}} .
    ?item    djht:{{item_type}}_version_id ?item_id .
    ?item    djht:account_id       ?account_id .
  }
  FILTER (?item_id = {{item_id}})
  FILTER (?account_id = {{account_id}})
  {%- if category_id is not none %}
  FILTER (?category_id = {{category_id}})
  {%- endif %}
}
{% endblock %}
