{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?row ?predicate ?object .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?row     rdf:type             djht:{{prefix}}PrivateLink .
    ?row     djht:{{item_type}}_version_id ?item_id .
    ?row     djht:id_string        ?id_string .
    ?row     ?predicate           ?object .

    ?item rdf:type                djht:{{prefix}} .
    ?item djht:{{item_type}}_version_id ?item_id .
    ?item djht:account_id          ?account_id .
  }
  FILTER (?item_id    = {{item_id}})
  FILTER (?account_id = {{account_id}})
  {%- if id_string is not none %}
  FILTER (?id_string = "{{id_string}}"^^xsd:string)
  {%- endif %}
}
{% endblock %}
