{% extends "prefixes.sparql" %}
{% block query %}
SELECT ?derived_from
WHERE {
  GRAPH <{{state_graph}}> {
    <{{item_uri}}>  rdf:type                djht:{{prefix}} ;
                    djht:derived_from        ?derived_from .
  }
}
{% endblock %}
