{% extends "prefixes.sparql" %}
{% block query %}
SELECT ?derived_from
WHERE {
  GRAPH <{{state_graph}}> {
    ?article    rdf:type                      sg:{{item_type|capitalize}} ;
                col:{{item_type}}_version_id  {{item_id}} ;
                col:derived_from              ?derived_from .
  }   
}
{% endblock %}
