{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?id ?title ?grant_code ?funder_name ?url
WHERE {
  GRAPH <{{state_graph}}> {
    ?funding          rdf:type                     sg:Funding .
    ?funding          col:id                       ?funding_id .

    ?link             rdf:type                     sg:{{prefix}}Funding .
    ?link             col:{{item_type}}_version_id ?{{item_type}}_version_id .
    ?link             col:funding_id               ?funding_id .

    OPTIONAL { ?funding  col:title                 ?title . }
    OPTIONAL { ?funding  col:grant_code            ?grant_code . }
    OPTIONAL { ?funding  col:funder_name           ?funder_name . }
    OPTIONAL { ?funding  col:url                   ?url . }

    {%- if account_id is not none %}
    ?item             rdf:type                     sg:{{prefix}} .
    ?item             col:{{item_type}}_version_id ?{{item_type}}_version_id .
    ?item             col:account_id               {{account_id}} .
    {%- endif %}
  }
  {%- if item_id is not none %}
  FILTER (?{{item_type}}_version_id = {{item_id}})
  {%- endif %}
{%- if filters is not none %}{{ filters }}{% endif %}
}
{% endblock %}
