{% extends "prefixes.sparql" %}
{% block query %}
SELECT ?group_id ?group_name
WHERE {
  GRAPH <{{state_graph}}> {
    ?group           rdf:type                 djht:InstitutionGroup .
    ?group           djht:id                   ?group_id .
    ?group           djht:name                 ?group_name .
  }
{%- if startswith %}
FILTER (STRSTARTS(STR(?group_name), "{{ group_name | safe }}"))
{%- else %}
FILTER (STR(?group_name) = "{{ group_name | safe }}")
{%- endif %}
}
{% endblock %}
