{% extends "prefixes.sparql" %}
{% block query %}
SELECT ?id ?parent_id ?name ?association
WHERE {
  GRAPH <{{state_graph}}> {
    ?group           rdf:type                 djht:InstitutionGroup .
    ?group           djht:id                   ?id .
    OPTIONAL { ?group           djht:name                 ?name . }
    OPTIONAL { ?group           djht:parent_id            ?parent_id . }
    OPTIONAL { ?group           djht:association_criteria ?association . }
  }
{% if filters is not none %}{{ filters | safe }}{% endif %}
}
{% endblock %}
