{% extends "prefixes.sparql" %}
{% block query %}
SELECT ?id
WHERE {
  GRAPH <{{state_graph}}> {
    ?item rdf:type    sg:{{item_type}} .
    {% if 'Article' == item_type %}
    ?item col:article_id ?id .
    {% elif 'Collection' == item_type %}
    ?item col:collection_id ?id .
    {% else %}
    ?item col:id      ?id .
    {% endif %}
  }
}
ORDER BY DESC(?id)
LIMIT 1
{% endblock %}
