{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?name ?url
WHERE {
  GRAPH <{{state_graph}}> {
    ?row             rdf:type                 sg:License .
    ?row             col:name                 ?name .
    OPTIONAL { ?row  col:url                  ?url . }
  }
}
{% endblock %}
