{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?id ?name ?url ?type
WHERE {
  GRAPH <{{state_graph}}> {
    ?url             rdf:type                 djht:License ;
                     djht:id                   ?id ;
                     djht:type/rdfs:label      ?type ;
                     djht:name                 ?name .
  }
  {%- if license_id is defined: %}
  FILTER (?id = {{license_id}})
  {%- endif %}
}
ORDER BY ASC(?type) ?name
{% endblock %}
