{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?group_uuid         ?uuid
                ?metadata_read      ?metadata_edit      ?metadata_remove
                ?data_read          ?data_edit          ?data_remove
                ?account_uuid       ?is_supervisor      ?order_index
                ?is_inferred        (?rest AS ?originating_blank_node)
WHERE {
  GRAPH <{{state_graph}}> {
    ?group_uri         rdf:type                 djht:InstitutionGroup .
    ?group_uri         djht:members             ?members .
    ?members           rdf:rest*                ?rest .
    ?rest              rdf:first                ?member_uri .
    ?rest              djht:index               ?order_index .
    ?member_uri        rdf:type                 djht:Member .
    ?member_uri        djht:account             ?account .

    ?member_uri        djht:metadata_read       ?metadata_read .
    ?member_uri        djht:metadata_edit       ?metadata_edit .
    ?member_uri        djht:metadata_remove     ?metadata_remove .
    ?member_uri        djht:data_read           ?data_read .
    ?member_uri        djht:data_edit           ?data_edit .
    ?member_uri        djht:data_remove         ?data_remove .
    BIND("true"^^xsd:boolean AS ?is_inferred)

    BIND(STRAFTER(STR(?group_uri), "group:") AS ?group_uuid)
    BIND(STRAFTER(STR(?member_uri), "member:") AS ?uuid)
    BIND(STRAFTER(STR(?account), "account:") AS ?account_uuid)
  }
FILTER (?group_uri = <group:{{group_uuid}}>)
}
{% endblock %}
