{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?download_url ?doi ?title
WHERE {
  GRAPH <{{state_graph}}> {
    ?article        rdf:type         sg:Article ;
                    col:article_version_id ?article_version_id ;
                    col:doi          ?doi ;
                    col:title        ?title .
    {
      ?link         rdf:type         sg:ArticleFile ;
                    col:article_version_id ?article_version_id ;
                    col:file_id      ?file_id .
      ?file         rdf:type         sg:File ;
                    col:id           ?file_id ;
                    col:download_url ?download_url .
    }
    UNION
    {
      ?article      col:data_link    ?download_url .
    }
  }
{%- if filters is not none %}{{ filters }}{% endif %}
}
{% endblock %}
