{# Find the latest version of each dataset for which one of the conditions in
   the UNION clause holds and return some properties of these dataset versions.
   Filters restrict the values of ?data_url. #}
{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?doi ?title
WHERE {
  GRAPH <{{state_graph}}> {
    ?dataset  a               djht:Dataset ;
              djht:container   ?container ;
              djht:version     ?version ;
              djht:title       ?title ;
              djht:doi         ?doi .
    {
      SELECT ?container (MAX(?i_version) AS ?version)
      WHERE {
        GRAPH <{{state_graph}}> {
          ?i_dataset  a               djht:Dataset ;
                      djht:container   ?container ;
                      djht:version     ?i_version .
          { ?i_dataset  djht:files/rdf:rest*/rdf:first  ?file .
            ?file       a                              djht:File ;
                        djht:is_link_only               true ;
                        djht:download_url               ?data_url . } UNION
          { ?i_dataset  djht:data_link                  ?data_url . }
        }
        {%- if filters is not none %}{{ filters | safe }}{% endif %}
      }
      GROUP BY ?container
    }
  }
}
{% endblock %}
