{# Find the latest version of each article for which one of the conditions in
   the UNION clause holds and return some properties of these article versions.
   Filters restrict the values of ?data_url. #}
{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?doi ?title
WHERE {
  GRAPH <{{state_graph}}> {
    ?article  a               djht:Article ;
              col:container   ?container ;
              col:version     ?version ;
              col:title       ?title ;
              col:doi         ?doi .
    {
      SELECT ?container (MAX(?i_version) AS ?version)
      WHERE {
        GRAPH <{{state_graph}}> {
          ?i_article  a               djht:Article ;
                      col:container   ?container ;
                      col:version     ?i_version .
          { ?i_article  col:files/rdf:rest*/rdf:first  ?file .
            ?file       a                              djht:File ;
                        col:is_link_only               true ;
                        col:download_url               ?data_url . } UNION
          { ?i_article  col:data_link                  ?data_url . }
        }
        {{ filters }}
      }
      GROUP BY ?container
    }
  }
}
{% endblock %}
