{% extends "prefixes.sparql" %}
{% block query %}

SELECT ?year (SUM(IF(?is_first_version, 1, 0)) AS ?new)
               (SUM(IF(!?is_first_version, 1, 0)) AS ?revisions)
               ?group_id
WHERE {
  GRAPH <https://data.4tu.nl> {
    ?container a djht:DatasetContainer ;
               djht:published_versions/rdf:rest*/rdf:first ?dataset ;
               djht:published_versions/rdf:first ?first_version .

    ?dataset   djht:posted_date ?date ;
               djht:group_id ?group_id .
  }

  BIND((?dataset = ?first_version) AS ?is_first_version)
  BIND(STR(YEAR(?date)) AS ?year)
  {% if filters is not none %}{{ filters | safe }}{% endif %}

}
GROUP BY ?year ?group_id
ORDER BY ASC(?year)
{% endblock %}
