{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?id_string ?is_active ?whom ?purpose ?expires_date ?uuid
                (?link AS ?uri) (?rest AS ?originating_blank_node)
                ?order_index
WHERE {
  GRAPH <{{state_graph}}> {
    ?item_uri          djht:private_links/rdf:rest* ?rest .
    ?rest              rdf:first                ?link ;
                       djht:index               ?order_index .
    ?item_uri          djht:container           ?container .
    ?container         rdf:type/rdfs:subClassOf djht:Container .
    ?link              rdf:type                 djht:PrivateLink ;
                       djht:id                   ?id_string .
    OPTIONAL { ?link   djht:is_active            ?is_active . }
    OPTIONAL { ?link   djht:whom                 ?whom . }
    OPTIONAL { ?link   djht:purpose              ?purpose . }
    OPTIONAL { ?link   djht:expires_date         ?expires_date . }
    {%- if account_uuid is not none %}
    ?container         djht:account              <account:{{account_uuid}}> .
    {%- endif %}
  }
  {%- if id_string is not none %}
  FILTER(?id_string = "{{id_string | safe}}"^^xsd:string)
  {%- endif %}
  {%- if item_uri is not none %}
  FILTER(?item_uri = <{{item_uri}}>)
  {%- endif %}

  BIND(STRAFTER(STR(?link), "private_link:") AS ?uuid)
}
{% endblock %}
