{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?id ?url
WHERE {
  GRAPH <{{state_graph}}> {
    ?row             rdf:type                 sg:{{prefix}}Reference .
    ?row             col:id                   ?id .
    ?row             col:{{item_type}}_version_id ?{{item_type}}_version_id .
    ?row             col:url                  ?url .
    {%- if item_id is not none %}
    ?item            rdf:type                 sg:{{prefix}} .
    ?item            col:{{item_type}}_version_id ?{{item_type}}_version_id .
    {%- if account_id is not none %}
    ?item           col:account_id           {{account_id}} .
    {%- endif %}
    {%- endif %}
  }
  FILTER (?{{item_type}}_version_id = {{item_id}})
{%- if filters is not none %}{{ filters }}{% endif %}
}
{% endblock %}
