{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?institution SUM(?size) AS ?total_size
WHERE
{
  { SELECT DISTINCT MIN(?posted_date) AS ?date
                    ?size ?gid
    WHERE {
      GRAPH <{{state_graph}}> {
        ?container  a                                           djht:DatasetContainer ;
                    djht:latest_published_version/djht:group_id ?gid ;
                    djht:published_versions/rdf:rest*/rdf:first ?dataset .
        ?dataset    djht:posted_date                            ?posted_date .
        ?dataset    djht:data_link_size                         ?size .
      }
    }
  }
  BIND (   1*(?gid=28586 OR ?gid=28628) #Delft
         + 2*(?gid=28589 OR ?gid=28631) #Eindhoven
         + 3*(?gid=28592 OR ?gid=28634) #Twente
         + 4*(?gid=28595)               #Wageningen
         AS ?institution_num )
  VALUES (?institution_num ?institution) {
    (0 "other") (1 "Delft") (2 "Eindhoven") (3 "Twente") (4 "Wageningen")
  }
  {% if filters is not none %}{{ filters | safe }}
  {% endif %}
}
ORDER BY ?institution
{% endblock %}
