{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?computed_md5 ?bytes
WHERE {
  GRAPH <{{state_graph}}> {
    ?file           rdf:type            sg:File .
    ?file           col:computed_md5    ?computed_md5 .
    ?file           col:size            ?bytes .
  }
{%- if filters is not none %}{{ filters }}{% endif %}
}
{% endblock %}
