{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?file_id ?bytes
WHERE {
  GRAPH <{{state_graph}}> {
    ?file           rdf:type            sg:File .
    ?file           col:id              ?file_id .
    ?file           col:size            ?bytes .
  }
{%- if filters is not none %}{{ filters }}{% endif %}
}
{% endblock %}
