{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?uuid ?request_date ?reminder_date ?assigned_to ?status
                ?account_uuid ?dataset_uuid ?dataset_title ?group_name
                ?submitter_first_name ?submitter_last_name ?submitter_email
WHERE {
  GRAPH <{{state_graph}}> {
    ?review             rdf:type                 djht:Review ;
                        djht:dataset              ?dataset .

    OPTIONAL { ?review  djht:request_date         ?request_date . }
    OPTIONAL { ?review  djht:reminder_date        ?reminder_date . }
    OPTIONAL { ?review  djht:assigned_to          ?assigned_to . }
    OPTIONAL { ?review  djht:status               ?status . }

    ?dataset            djht:container            ?container_uri ;
                        djht:title                ?dataset_title .

    ?container_uri      djht:account              ?account .

    OPTIONAL {
      ?group            rdf:type                 djht:InstitutionGroup ;
                        djht:id                   ?group_id ;
                        djht:name                 ?group_name .
      ?dataset          djht:group_id             ?group_id .
    }

    OPTIONAL { ?account djht:email                ?submitter_email . }
    OPTIONAL { ?account djht:first_name           ?submitter_first_name . }
    OPTIONAL { ?account djht:last_name            ?submitter_last_name . }
    OPTIONAL { ?account djht:institution_id       ?institution_id . }

    BIND(STRAFTER(STR(?dataset), "dataset:")  AS ?dataset_uuid)
    BIND(STRAFTER(STR(?account), "account:")  AS ?account_uuid)
    BIND(STRAFTER(STR(?review),  "review:")   AS ?uuid)
  }
  FILTER NOT EXISTS { ?dataset djht:published_date ?published_date . }
{%- if assigned_to is not none %}
  FILTER (?assigned_to = <account:{{assigned_to}}>)
{%- if review_uuid is not none: %}
  FILTER (?review = <review:{{review_uuid}}>)
{%- endif %}
{%- else %}
  FILTER (! BOUND(?assigned_to))
{%- endif %}{% if status is not none %}
  FILTER (?status = {{status}})
{%- endif %}
}
{% endblock %}
