{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?uuid ?request_date ?reminder_date ?assigned_to
                ?account_uuid ?dataset_uuid ?dataset_title ?group_name
                ?submitter_first_name ?submitter_last_name ?submitter_email
                ?published_date ?container_uuid ?dataset_version ?declined_date
                ?reviewer_email ?reviewer_first_name ?reviewer_last_name
                ?modified_date (?status_label AS ?status) ?has_published_version
WHERE {
  GRAPH <{{state_graph}}> {
    ?review             rdf:type                 djht:Review ;
                        djht:dataset              ?dataset .

    OPTIONAL { ?review  djht:request_date         ?request_date . }
    OPTIONAL { ?review  djht:reminder_date        ?reminder_date . }
    OPTIONAL {
      ?review           djht:status               ?status_uri .
      ?status_uri       rdfs:label                ?status_label .
    }

    ?dataset            djht:container            ?container_uri ;
                        djht:title                ?dataset_title .
    OPTIONAL { ?dataset djht:published_date       ?published_date . }
    OPTIONAL { ?dataset djht:declined_date        ?declined_date . }
    OPTIONAL { ?dataset djht:modified_date        ?modified_date . }
    OPTIONAL { ?dataset djht:version              ?dataset_version . }

    ?container_uri      djht:account              ?account .

    OPTIONAL { ?container_uri djht:latest_published_version ?published_version . }
    OPTIONAL {
      ?group            rdf:type                 djht:InstitutionGroup ;
                        djht:id                   ?group_id ;
                        djht:name                 ?group_name .
      ?dataset          djht:group_id             ?group_id .
    }

    OPTIONAL { ?account djht:email                ?submitter_email . }
    OPTIONAL { ?account djht:first_name           ?submitter_first_name . }
    OPTIONAL { ?account djht:last_name            ?submitter_last_name . }
    OPTIONAL { ?account djht:institution_id       ?institution_id . }

    OPTIONAL {
      ?review  djht:assigned_to          ?assigned_to .

      # OPTIONAL within OPTIONAL because if ?assigned_to is unbound,
      # the following OPTIONAL bindings shouldn't just bind freely to anything
      # with these predicates.
      OPTIONAL { ?assigned_to djht:email            ?reviewer_email . }
      OPTIONAL { ?assigned_to djht:first_name       ?reviewer_first_name . }
      OPTIONAL { ?assigned_to djht:last_name        ?reviewer_last_name . }
    }

    BIND(STRAFTER(STR(?container_uri), "container:") AS ?container_uuid)
    BIND(STRAFTER(STR(?dataset), "dataset:")  AS ?dataset_uuid)
    BIND(STRAFTER(STR(?account), "account:")  AS ?account_uuid)
    BIND(STRAFTER(STR(?review),  "review:")   AS ?uuid)
    BIND(BOUND(?published_version)            AS ?has_published_version)
  }
{%- if assigned_to is not none %}
  FILTER (?assigned_to = <account:{{assigned_to}}>)
{%- if review_uuid is not none: %}
  FILTER (?review = <review:{{review_uuid}}>)
{%- endif %}
{%- endif %}
{%- if status is not none %}
  FILTER (?status_uri = djht:Review{{status | safe}})
{%- endif %}
{% if filters is not none %}{{ filters | safe }}{% endif %}
}
{% endblock %}
