{% extends "prefixes.sparql" %}
{% block query %}
SELECT ?downloads ?views ?shares ?cites
WHERE {
  GRAPH <{{state_graph}}> {
    ?container            a                    djht:DatasetContainer ;
                          djht:article_id       {{article_id}} .
    OPTIONAL { ?container djht:total_downloads  ?downloads . }
    OPTIONAL { ?container djht:total_views      ?views .     }
    OPTIONAL { ?container djht:total_shares     ?shares .    }
    OPTIONAL { ?container djht:total_cites      ?cites .     }
  }
}
{% endblock %}
