{% extends "prefixes.sparql" %}
{% block query %}
SELECT (COUNT(DISTINCT ?collection_id) AS ?collections)
WHERE {
  GRAPH <{{state_graph}}> {
    ?collection     rdf:type            djht:Collection .
    ?collection     djht:collection_id   ?collection_id .
    ?collection     djht:is_public       "true"^^xsd:boolean .
  }
{%- if filters is not none %}{{ filters | safe }}{% endif %}
}
{% endblock %}
