{% extends "prefixes.sparql" %}
{% block query %}
SELECT (COUNT(DISTINCT ?dataset_id) AS ?datasets)
WHERE {
  GRAPH <{{state_graph}}> {
    ?dataset        rdf:type            djht:Dataset .
    ?dataset        djht:dataset_id     ?dataset_id .
    ?dataset        djht:is_public      "true"^^xsd:boolean .
  }
{%- if filters is not none %}{{ filters | safe }}{% endif %}
}
{% endblock %}
