{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?uuid ?title ?source_id ?taxonomy_id
WHERE {
  GRAPH <{{state_graph}}> {
    ?parent_category     rdf:type         sg:Category ;
                         col:id           ?parent_id .
    ?category            rdf:type         sg:Category ;
                         col:title        ?title ;
                         col:parent_id    ?parent_id .
    OPTIONAL { ?category col:source_id    ?source_id . }
    OPTIONAL { ?category col:taxonomy_id  ?taxonomy_id . }

    BIND(STRAFTER(STR(?category), "category:") AS ?uuid)
  }
  FILTER (?parent_category = <{{category_uri}}>)
}
{% endblock %}
