{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    {%- if download_url is not none %}
    ?file              col:download_url        ?download_url .
    {%- endif%}{% if computed_md5 is not none %}
    ?file              col:computed_md5        ?computed_md5 .
    {%- endif%}{% if viewer_type is not none %}
    ?file              col:viewer_type         ?viewer_type .
    {%- endif%}{% if preview_state is not none %}
    ?file              col:preview_state       ?preview_state .
    {%- endif%}{% if file_size is not none %}
    ?file              col:size                ?size .
    {%- endif%}{% if status is not none %}
    ?file              col:status              ?status .
    {%- endif%}
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    {%- if download_url is not none %}
    ?file              col:download_url        "{{download_url}}"^^xsd:string .
    {%- endif%}{% if computed_md5 is not none %}
    ?file              col:computed_md5        "{{computed_md5}}"^^xsd:string .
    {%- endif%}{% if viewer_type is not none %}
    ?file              col:viewer_type         "{{viewer_type}}"^^xsd:string .
    {%- endif%}{% if preview_state is not none %}
    ?file              col:preview_state       "{{preview_state}}"^^xsd:string .
    {%- endif%}{% if file_size is not none %}
    ?file              col:size                {{file_size}} .
    {%- endif%}{% if status is not none %}
    ?file              col:status              "{{status}}"^^xsd:string .
    {%- endif%}
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?file              rdf:type                sg:File .

    {#- Ensure that the account_id associated with the ?file can modify its
     #- properties. #}
    ?article           col:files/rdf:rest*/rdf:first ?file ;
                       col:container/col:account_id  {{account_id}} .

    OPTIONAL { ?file   col:id                  ?id . }
    OPTIONAL { ?file   col:download_url        ?download_url . }
    OPTIONAL { ?file   col:computed_md5        ?computed_md5 . }
    OPTIONAL { ?file   col:viewer_type         ?viewer_type . }
    OPTIONAL { ?file   col:preview_state       ?preview_state . }
    OPTIONAL { ?file   col:size                ?size . }
    OPTIONAL { ?file   col:status              ?status . }
  }
  FILTER (?file = <file:{{file_uuid}}>)
}
{% endblock %}
