{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?review          col:assigned_to           ?assigned_to .
    {% if status is not none %}
    ?review          col:status                ?status .
    {%- endif%}{% if reminder_date is not none %}
    ?review          col:reminder_date         ?reminder_date .
    {%- endif%}
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    {%- if assigned_to is not none %}
    ?review          col:assigned_to          "{{assigned_to}}"^^xsd:integer .
    {%- endif%}{% if status is not none %}
    ?review          col:status               "{{status}}"^^xsd:string .
    {%- endif%}{% if reminder_date is not none %}
    ?review          col:reminder_date        "{{reminder_date}}"^^xsd:dateTime .
    {%- endif%}
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?review              rdf:type                  sg:Review .
    OPTIONAL { ?review   col:assigned_to           ?assigned_to . }
    OPTIONAL { ?review   col:status                ?status . }
    OPTIONAL { ?review   col:reminder_date         ?reminder_date . }
  }
  FILTER (?review = <{{review_uri}}>)
}
{% endblock %}
