{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?dataset          djht:format_annotation      ?format_annotation .
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    ?dataset          djht:format_annotation      {{format_annotation | safe}} .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?dataset   rdf:type          djht:Dataset .
    OPTIONAL { ?dataset   djht:format_annotation  ?format_annotation . }
  }
  FILTER (?dataset = <dataset:{{dataset_uuid}}>)
}
{% endblock %}
