{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    {%- if title is not none %}
    ?article           col:title                ?title .
    {%- endif%}{% if description is not none %}
    ?article           col:description          ?description .
    {%- endif%}{% if resource_doi is not none %}
    ?article           col:resource_doi         ?resource_doi .
    {%- endif%}{% if resource_title is not none %}
    ?article           col:resource_title       ?resource_title .
    {%- endif%}{% if license_id is not none %}
    ?article           col:license_id           ?license_id .
    {%- endif%}{% if time_coverage is not none %}
    ?article           col:time_coverage        ?time_coverage .
    {%- endif%}{% if publisher is not none %}
    ?article           col:publisher            ?publisher .
    {%- endif%}{% if language is not none %}
    ?article           col:language             ?language .
    {%- endif%}{% if format is not none %}
    ?article           col:format               ?format .
    {%- endif%}{% if contributors is not none %}
    ?article           col:contributors         ?contributors .
    {%- endif%}{% if license_remarks is not none %}
    ?article           col:license_remarks      ?license_remarks .
    {%- endif%}{% if geolocation is not none %}
    ?article           col:geolocation          ?geolocation .
    {%- endif%}{% if longitude is not none %}
    ?article           col:longitude            ?longitude .
    {%- endif%}{% if latitude is not none %}
    ?article           col:latitude             ?latitude .
    {%- endif%}{% if data_link is not none %}
    ?article           col:data_link            ?data_link .
    {%- endif%}{% if derived_from is not none %}
    ?article           col:derived_from         ?derived_from .
    {%- endif%}{% if same_as is not none %}
    ?article           col:same_as              ?same_as .
    {%- endif%}{% if organizations is not none %}
    ?article           col:organizations        ?organizations .
    {%- endif%}{% if defined_type_name is not none %}
    ?article           col:defined_type_name    ?defined_type_name .
    {%- endif%}{% if defined_type is not none %}
    ?article           col:defined_type         ?defined_type .
    {%- endif%}
    ?article           col:modified_date        ?modified_date .
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    {%- if title is not none %}
    ?article           col:title                "{{title}}"^^xsd:string .
    {%- endif%}{% if description is not none %}
    ?article           col:description          "{{description}}"^^xsd:string .
    {%- endif%}{% if resource_doi is not none %}
    ?article           col:resource_doi         "{{resource_doi}}"^^xsd:string .
    {%- endif%}{% if resource_title is not none %}
    ?article           col:resource_title       "{{resource_title}}"^^xsd:string .
    {%- endif%}{% if license_id is not none %}
    ?article           col:license_id           {{license_id}} .
    {%- endif%}{% if time_coverage is not none %}
    ?article           col:time_coverage        "{{time_coverage}}"^^xsd:string .
    {%- endif%}{% if publisher is not none %}
    ?article           col:publisher            "{{publisher}}"^^xsd:string .
    {%- endif%}{% if language is not none %}
    ?article           col:language             "{{language}}"^^xsd:string .
    {%- endif%}{% if format is not none %}
    ?article           col:format               "{{format}}"^^xsd:string .
    {%- endif%}{% if contributors is not none %}
    ?article           col:contributors         "{{contributors}}"^^xsd:string .
    {%- endif%}{% if license_remarks is not none %}
    ?article           col:license_remarks      "{{license_remarks}}"^^xsd:string .
    {%- endif%}{% if geolocation is not none %}
    ?article           col:geolocation          "{{geolocation}}"^^xsd:string .
    {%- endif%}{% if longitude is not none %}
    ?article           col:longitude            "{{longitude}}"^^xsd:string .
    {%- endif%}{% if latitude is not none %}
    ?article           col:latitude             "{{latitude}}"^^xsd:string .
    {%- endif%}{% if data_link is not none %}
    ?article           col:data_link            "{{data_link}}"^^xsd:string .
    {%- endif%}{% if derived_from is not none %}
    ?article           col:derived_from         "{{derived_from}}"^^xsd:string .
    {%- endif%}{% if same_as is not none %}
    ?article           col:same_as              "{{same_as}}"^^xsd:string .
    {%- endif%}{% if organizations is not none %}
    ?article           col:organizations        "{{organizations}}"^^xsd:string .
    {%- endif%}{% if defined_type_name is not none %}
    ?article           col:defined_type_name    "{{defined_type_name}}"^^xsd:string .
    {%- endif%}{% if defined_type is not none %}
    ?article           col:defined_type         {{defined_type}} .
    {%- endif%}
    ?article           col:modified_date        "{{modified_date}}"^^xsd:string .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?article            rdf:type                 sg:Article .
    ?article            col:article_id           ?article_id .
    ?article            col:account_id           ?account_id .
    ?article            col:title                ?title .

    OPTIONAL { ?article col:description          ?description . }
    OPTIONAL { ?article col:license_id           ?license_id . }
    OPTIONAL { ?article col:resource_doi         ?resource_doi . }
    OPTIONAL { ?article col:resource_title       ?resource_title . }
    OPTIONAL { ?article col:modified_date        ?modified_date . }
    OPTIONAL { ?article col:publisher             ?publisher . }
    OPTIONAL { ?article col:language              ?language . }
    OPTIONAL { ?article col:time_coverage         ?time_coverage . }
    OPTIONAL { ?article col:geolocation           ?geolocation . }
    OPTIONAL { ?article col:longitude             ?longitude . }
    OPTIONAL { ?article col:latitude              ?latitude . }
    OPTIONAL { ?article col:format                ?format . }
    OPTIONAL { ?article col:organizations         ?organizations . }
    OPTIONAL { ?article col:data_link             ?data_link . }
    OPTIONAL { ?article col:same_as               ?same_as . }
    OPTIONAL { ?article col:derived_from          ?derived_from . }
    OPTIONAL { ?article col:contributors          ?contributors . }
    OPTIONAL { ?article col:license_remarks       ?license_remarks . }
    OPTIONAL { ?article col:defined_type_name     ?defined_type_name . }
    OPTIONAL { ?article col:defined_type          ?defined_type . }
  }
{%- if account_id is not none: %}
  FILTER (?account_id = {{account_id}})
{%- endif %}
  FILTER (?article_id = {{article_id}})
}
{% endblock %}
