{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    {%- if is_active is not none %}
    ?account          djht:is_active             ?is_active .
    {%- endif%}{% if email is not none %}
    ?account          djht:email                 ?email .
    {%- endif%}{% if job_title is not none %}
    ?account          djht:job_title             ?job_title .
    {%- endif%}{% if first_name is not none %}
    ?account          djht:first_name            ?first_name .
    {%- endif%}{% if last_name is not none %}
    ?account          djht:last_name             ?last_name .
    {%- endif%}{% if location is not none %}
    ?account          djht:location              ?location .
    {%- endif%}{% if biography is not none %}
    ?account          djht:biography             ?biography .
    {%- endif%}{% if institution_user_id is not none %}
    ?account          djht:institution_user_id   ?institution_user_id .
    {%- endif%}{% if institution_id is not none %}
    ?account          djht:institution_id        ?institution_id .
    {%- endif%}{% if pending_quota_request is not none %}
    ?account          djht:pending_quota_request ?pending_quota_request .
    {%- endif%}{% if used_quota_public is not none %}
    ?account          djht:used_quota_public     ?used_quota_public .
    {%- endif%}{% if used_quota_private is not none %}
    ?account          djht:used_quota_private    ?used_quota_private .
    {%- endif%}{% if maximum_file_size is not none %}
    ?account          djht:maximum_file_size     ?maximum_file_size .
    {%- endif%}{% if quota is not none %}
    ?account          djht:quota                 ?quota .
    {%- endif%}{% if modified_date is not none %}
    ?account          djht:modified_date         ?modified_date .
    {%- endif%}{% if group_id is not none %}
    ?account          djht:group_id              ?group_id .
    {%- endif%}
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    {%- if is_active is not none %}
    ?account          djht:is_active           {{is_active}} .
    {%- endif%}{% if email is not none %}
    ?account          djht:email               "{{email}}"^^xsd:string .
    {%- endif%}{% if job_title is not none %}
    ?account          djht:job_title           "{{job_title}}"^^xsd:string .
    {%- endif%}{% if first_name is not none %}
    ?account          djht:first_name          "{{first_name}}"^^xsd:string .
    {%- endif%}{% if last_name is not none %}
    ?account          djht:last_name           "{{last_name}}"^^xsd:string .
    {%- endif%}{% if location is not none %}
    ?account          djht:location            "{{location}}"^^xsd:string .
    {%- endif%}{% if biography is not none %}
    ?account          djht:biography           "{{biography}}"^^xsd:string .
    {%- endif%}{% if institution_user_id is not none %}
    ?account          djht:institution_user_id {{institution_user_id}} .
    {%- endif%}{% if institution_id is not none %}
    ?account          djht:institution_id      {{institution_id}} .
    {%- endif%}{% if pending_quota_request is not none %}
    ?account          djht:pending_quota_request {{pending_quota_request}} .
    {%- endif%}{% if used_quota_public is not none %}
    ?account          djht:used_quota_public   {{used_quota_public}} .
    {%- endif%}{% if used_quota_private is not none %}
    ?account          djht:used_quota_private  {{used_quota_private}} .
    {%- endif%}{% if maximum_file_size is not none %}
    ?account          djht:maximum_file_size   {{maximum_file_size}} .
    {%- endif%}{% if quota is not none %}
    ?account          djht:quota               {{quota}} .
    {%- endif%}{% if modified_date is not none %}
    ?account          djht:modified_date       "{{modified_date}}"^^xsd:string .
    {%- endif%}{% if group_id is not none %}
    ?account          djht:group_id            {{group_id}} .
    {%- endif%}
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?account              rdf:type                  djht:Account .

    OPTIONAL { ?account   djht:is_active             ?is_active . }
    OPTIONAL { ?account   djht:email                 ?email . }
    OPTIONAL { ?account   djht:job_title             ?job_title . }
    OPTIONAL { ?account   djht:first_name            ?first_name . }
    OPTIONAL { ?account   djht:last_name             ?last_name . }
    OPTIONAL { ?account   djht:location              ?location . }
    OPTIONAL { ?account   djht:biography             ?biography . }
    OPTIONAL { ?account   djht:institution_user_id   ?institution_user_id . }
    OPTIONAL { ?account   djht:institution_id        ?institution_id . }
    OPTIONAL { ?account   djht:pending_quota_request ?pending_quota_request . }
    OPTIONAL { ?account   djht:used_quota_public     ?used_quota_public . }
    OPTIONAL { ?account   djht:used_quota_private    ?used_quota_private . }
    OPTIONAL { ?account   djht:maximum_file_size     ?maximum_file_size . }
    OPTIONAL { ?account   djht:quota                 ?quota . }
    OPTIONAL { ?account   djht:modified_date         ?modified_date . }
    OPTIONAL { ?account   djht:group_id              ?group_id . }
  }
  FILTER (?account = <account:{{account_uuid}}>)
}
{% endblock %}
