{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?item      djht:doi          ?doi .
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    ?item      djht:doi          {{doi | safe}} .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?item      rdf:type          djht:{{item_type.capitalize()}} .
    OPTIONAL { ?item djht:doi ?doi . }
  }
  FILTER (?item = <{{item_type}}:{{item_uuid}}>)
}
{% endblock %}
