{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?dataset   djht:last_seen_by_reviewer ?timestamp .
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    ?dataset   djht:last_seen_by_reviewer "{{timestamp}}"^^xsd:dateTime .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?dataset   rdf:type          djht:Dataset .
    OPTIONAL { ?dataset djht:last_seen_by_reviewer ?timestamp . }
  }
  FILTER (?dataset = <dataset:{{dataset_uuid}}>)
}
{% endblock %}
