{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    {%- if is_active is not none %}
    ?link     col:is_active        ?is_active .
    {%- endif %}{% if expires_date is not none %}
    ?link     col:expires_date     ?expires_date .
    {%- endif %}{% if read_only is not none %}
    ?link     col:read_only        ?read_only .
    {%- endif %}
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    {%- if is_active is not none %}
    ?link     col:is_active        {{is_active}} .
    {%- endif %}{% if expires_date is not none %}
    ?link     col:expires_date     "{{expires_date}}"^^xsd:string .
    {%- endif %}{% if read_only is not none %}
    ?link     col:read_only        {{read_only}} .
    {%- endif %}
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?container       rdf:type/rdf:type    sg:Container ;
                     col:account_id       ?account_id ;
                     col:draft            ?item_uri .

    ?item_uri        col:private_links/rdf:rest*/rdf:first ?link .

    ?link            rdf:type             sg:PrivateLink ;
                     col:id               ?id_string .

    OPTIONAL { ?link col:is_active        ?is_active . }
    OPTIONAL { ?link col:expires_date     ?expires_date . }
    OPTIONAL { ?link col:read_only        ?read_only . }
  }
  FILTER (?item_uri   = <{{item_uri}}>)
  FILTER (?account_id = {{account_id}})
  {%- if id_string is not none %}
  FILTER (?id_string  = "{{id_string}}"^^xsd:string)
  {%- endif %}
}
{% endblock %}
