{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?session djht:editable   ?editable .
    ?session djht:name       ?name .
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    ?session djht:name       "{{name | safe}}"^^xsd:string .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?session  rdf:type                   djht:Session .
    ?session  djht:account               ?account .
    ?session  djht:name                  ?name .
    ?session  djht:editable              1 .
  }
  FILTER (?account = <account:{{account_uuid}}>)
  FILTER (?session = <session:{{session_uuid}}>)
}
{% endblock %}
