{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    {%- if full_name is not none %}
    ?author       djht:full_name             ?full_name .
    {%- endif %}{% if first_name is not none %}
    ?author       djht:first_name            ?first_name .
    {%- endif%}{% if last_name is not none %}
    ?author       djht:last_name             ?last_name .
    {%- endif%}{% if email is not none %}
    ?author       djht:email                 ?email .
    {%- endif%}{% if orcid is not none %}
    ?author       djht:orcid_id              ?orcid .
    {%- endif%}{% if modified_date is not none %}
    ?author       djht:modified_date         ?modified_date .
    {%- endif%}
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    {%- if full_name is not none %}
    ?author       djht:full_name             {{full_name | safe }} .
    {%- endif %}{% if first_name is not none %}
    ?author       djht:first_name            {{first_name | safe}} .
    {%- endif%}{% if last_name is not none %}
    ?author       djht:last_name             {{last_name | safe}} .
    {%- endif%}{% if email is not none %}
    ?author       djht:email                 {{email | safe}} .
    {%- endif%}{% if orcid is not none %}
    ?author       djht:orcid_id              {{orcid | safe}} .
    {%- endif%}{% if modified_date is not none %}
    ?author       djht:modified_date         {{modified_date | safe}} .
    {%- endif%}
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?author       rdf:type                   djht:Author .
    ?author       djht:created_by            <account:{{created_by}}> .
    OPTIONAL { ?author   djht:first_name     ?first_name . }
    OPTIONAL { ?author   djht:last_name      ?last_name . }
    OPTIONAL { ?author   djht:full_name      ?full_name . }
    OPTIONAL { ?author   djht:email          ?email . }
    OPTIONAL { ?author   djht:modified_date  ?modified_date . }
  }
  FILTER (?author = <author:{{author_uuid}}>)
}
{% endblock %}
