{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    {%- if download_url is not none %}
    ?file              djht:download_url        ?download_url .
    {%- endif%}{% if computed_md5 is not none %}
    ?file              djht:computed_md5        ?computed_md5 .
    {%- endif%}{% if is_incomplete is not none %}
    ?file              djht:is_incomplete       ?is_incomplete .
    {%- endif%}{% if is_image is not none %}
    ?file              djht:is_image            ?is_image .
    {%- endif%}{% if viewer_type is not none %}
    ?file              djht:viewer_type         ?viewer_type .
    {%- endif%}{% if preview_state is not none %}
    ?file              djht:preview_state       ?preview_state .
    {%- endif%}{% if file_size is not none %}
    ?file              djht:size                ?size .
    {%- endif%}{% if status is not none %}
    ?file              djht:status              ?status .
    {%- endif%}{% if filesystem_location is not none %}
    ?file              djht:filesystem_location ?filesystem_location .
    {%- endif%}
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    {%- if download_url is not none %}
    ?file              djht:download_url        "{{download_url | safe}}"^^xsd:string .
    {%- endif%}{% if computed_md5 is not none %}
    ?file              djht:computed_md5        "{{computed_md5 | safe}}"^^xsd:string .
    {%- endif%}{% if is_incomplete is not none %}
    ?file              djht:is_incomplete       {{is_incomplete}} .
    {%- endif%}{% if is_image is not none %}
    ?file              djht:is_image            {{is_image | safe}} .
    {%- endif%}{% if viewer_type is not none %}
    ?file              djht:viewer_type         "{{viewer_type | safe}}"^^xsd:string .
    {%- endif%}{% if preview_state is not none %}
    ?file              djht:preview_state       "{{preview_state | safe}}"^^xsd:string .
    {%- endif%}{% if file_size is not none %}
    ?file              djht:size                {{file_size | safe}} .
    {%- endif%}{% if status is not none %}
    ?file              djht:status              "{{status | safe}}"^^xsd:string .
    {%- endif%}{% if filesystem_location is not none %}
    ?file              djht:filesystem_location "{{filesystem_location | safe}}"^^xsd:string .
    {%- endif%}
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?file              rdf:type                djht:File .

    {#- Ensure that the account_uuid associated with the ?file can modify its
     #- properties. #}
    ?dataset           djht:files/rdf:rest*/rdf:first ?file .
      {
      ?dataset           djht:container/djht:account    <account:{{account_uuid | safe}}> .
      } UNION {
        ?dataset         djht:collaborators/rdf:rest*/rdf:first ?collaborator .
        ?collaborator    djht:account ?account .
        ?collaborator    djht:data_edit "true"^^xsd:boolean .
    }

    OPTIONAL { ?file   djht:id                  ?id . }
    OPTIONAL { ?file   djht:filesystem_location ?filesystem_location . }
    OPTIONAL { ?file   djht:download_url        ?download_url . }
    OPTIONAL { ?file   djht:computed_md5        ?computed_md5 . }
    OPTIONAL { ?file   djht:is_incomplete       ?is_incomplete . }
    OPTIONAL { ?file   djht:is_image            ?is_image . }
    OPTIONAL { ?file   djht:viewer_type         ?viewer_type . }
    OPTIONAL { ?file   djht:preview_state       ?preview_state . }
    OPTIONAL { ?file   djht:size                ?size . }
    OPTIONAL { ?file   djht:status              ?status . }
  }
  FILTER (?file = <file:{{file_uuid | safe}}>)
}
{% endblock %}
