{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    {%- if is_active is not none %}
    ?link     djht:is_active        ?is_active .
    {%- endif %}{% if expires_date is not none %}
    ?link     djht:expires_date     ?expires_date .
    {%- endif %}{% if read_only is not none %}
    ?link     djht:read_only        ?read_only .
    {%- endif %}
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    {%- if is_active is not none %}
    ?link     djht:is_active        {{is_active}} .
    {%- endif %}{% if expires_date is not none %}
    ?link     djht:expires_date     "{{expires_date | safe}}"^^xsd:string .
    {%- endif %}{% if read_only is not none %}
    ?link     djht:read_only        {{read_only}} .
    {%- endif %}
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?container       rdf:type/rdfs:subClassOf djht:Container ;
                     djht:account              ?account ;
                     ?container_predicate      ?item_uri .

    ?item_uri        djht:private_links/rdf:rest*/rdf:first ?link .

    ?link            rdf:type             djht:PrivateLink ;
                     djht:id               ?id_string .

    OPTIONAL { ?link djht:is_active        ?is_active . }
    OPTIONAL { ?link djht:expires_date     ?expires_date . }
    OPTIONAL { ?link djht:read_only        ?read_only . }
  }
  FILTER (?container_predicate = djht:draft || ?container_predicate = djht:latest_published_version)
  FILTER (?item_uri   = <{{item_uri}}>)
  FILTER (?account    = <account:{{account_uuid}}>)
  {%- if id_string is not none %}
  FILTER (?id_string  = "{{id_string | safe}}"^^xsd:string)
  {%- endif %}
}
{% endblock %}
