{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?session col:editable   ?editable .
    ?session col:name       ?name .
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    ?session col:name       "{{name}}"^^xsd:string .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?session  rdf:type                  sg:Session .
    ?session  col:account_id            ?account_id .
    ?session  col:name                  ?name .
    ?session  col:editable              1 .
  }
  FILTER (?account_id = {{account_id}})
  FILTER (?session = <session:{{session_uuid}}>)
}
{% endblock %}
