{% extends "prefixes.sparql" %}
{% block query %}
{self.default_prefixes}
DELETE {
  GRAPH <{{state_graph}}> {
    ?embargo  ?predicate     ?object .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?article  rdf:type        sg:Article .
    ?article  col:article_id  {{article_id}} .
    ?article  col:account_id  {{account_id}} .

    ?embargo  rdf:type        sg:ArticleEmbargoOption .
    ?embargo  col:article_id  {{article_id}} .
    ?embargo  ?predicate      ?object .
  }
}
{% endblock %}
