{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?collection  ?predicate     ?object .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?collection  rdf:type          sg:Collection .
    ?collection  col:collection_id {{collection_id}} .
    ?collection  col:account_id    {{account_id}} .
    ?collection  ?predicate        ?object .
  }
}
{% endblock %}
