{% extends "prefixes.sparql" %}
{% block query %}
SELECT (COUNT(DISTINCT ?file) AS ?files)
       (SUM(?bytes) AS ?bytes)
WHERE {
  GRAPH <{{state_graph}}> {
    ?file           rdf:type            sg:File .
    ?file           col:size            ?bytes .
  }
{% if filters is not none %}{{ filters }}{% endif %}
}
{% endblock %}
