{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?article col:thumb  ?thumb .
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    ?article col:thumb  "/files/{{file_id}}/preview/{{file_id}}/thumb.png" .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?article rdf:type       sg:Article .
    ?article col:article_id ?article_id .
    ?article col:account_id {{account_id}} .
    ?article col:version    {{version}}.
    OPTIONAL { ?article col:thumb      ?thumb . }

    ?file    rdf:type       sg:File .
    ?file    col:id         ?file_id .

    ?link    rdf:type       sg:ArticleFile .
    ?link    col:article_id ?article_id .
    ?link    col:file_id    ?file_id .
  }
{% if filters is not none %}{{ filters }}{% endif %}
}
{% endblock %}
